// packages/vue-adapter/src/components/MarqueeRect.vue
<script setup lang="ts">
import type { BoundingBox } from '@svg-editor/core';

defineProps<{
  box: BoundingBox | null;
}>();
</script>

<template>
  <svg
    v-if="box"
    style="position: absolute; inset: 0; width: 100%; height: 100%; pointer-events: none"
  >
    <rect
      :x="box.x"
      :y="box.y"
      :width="box.width"
      :height="box.height"
      fill="rgba(0, 102, 255, 0.08)"
      stroke="#0066ff"
      stroke-width="1"
      stroke-dasharray="4 2"
    />
  </svg>
</template>

// packages/react-adapter/src/components/MarqueeRect.tsx
interface MarqueeRectProps {
  x: number;
  y: number;
  width: number;
  height: number;
}

export function MarqueeRect({ x, y, width, height }: MarqueeRectProps) {
  return (
    <svg
      style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', pointerEvents: 'none' }}
    >
      <rect
        x={x} y={y} width={width} height={height}
        fill="rgba(0, 102, 255, 0.1)"
        stroke="#0066FF"
        strokeWidth={1}
        strokeDasharray="4 2"
      />
    </svg>
  );
}
