// apps/demo-vue/src/components/ZoomControls.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useEditor, useEditorState } from '@andmarruda/svg-editor-vue';

const editor = useEditor();
const state = useEditorState();
const zoom = computed(() => Math.round((state.value.viewTransform.matrix[0] ?? 1) * 100));

function zoomBy(factor: number) {
  const [a, b, c, d, e, f] = state.value.viewTransform.matrix;
  editor.setViewTransform({
    matrix: [(a ?? 1) * factor, b ?? 0, c ?? 0, (d ?? 1) * factor, e ?? 0, f ?? 0],
  });
}
</script>

<template>
  <div
    style="
      position: absolute;
      right: 12px;
      bottom: 12px;
      display: flex;
      gap: 4px;
      align-items: center;
      background: white;
      border: 1px solid #ddd;
      padding: 4px;
      font-size: 12px;
    "
  >
    <button @click="zoomBy(0.9)">-</button>
    <span style="min-width: 44px; text-align: center">{{ zoom }}%</span>
    <button @click="zoomBy(1.1)">+</button>
  </div>
</template>

// apps/demo-react/src/components/ZoomControls.tsx
import { useEditor, useEditorState } from '@andmarruda/svg-editor-react';

export function ZoomControls() {
  const editor = useEditor();
  const state = useEditorState();
  const zoom = Math.round((state.viewTransform.matrix[0] ?? 1) * 100);

  const zoomBy = (factor: number) => {
    const [a, b, c, d, e, f] = state.viewTransform.matrix;
    editor.setViewTransform({
      matrix: [(a ?? 1) * factor, b ?? 0, c ?? 0, (d ?? 1) * factor, e ?? 0, f ?? 0],
    });
  };

  return (
    <div
      style={{
        position: 'absolute',
        right: 12,
        bottom: 12,
        display: 'flex',
        gap: 4,
        alignItems: 'center',
        background: 'white',
        border: '1px solid #ddd',
        padding: 4,
        fontSize: 12,
      }}
    >
      <button onClick={() => zoomBy(0.9)}>-</button>
      <span style={{ minWidth: 44, textAlign: 'center' }}>{zoom}%</span>
      <button onClick={() => zoomBy(1.1)}>+</button>
    </div>
  );
}
