// packages/react-adapter/src/components/Canvas.tsx
import { useRef, useEffect, useCallback, type PointerEvent } from 'react';
import type { NodeId, BoundingBox, ShapePreset } from '@andmarruda/svg-editor-core';
import {
  createNodeFromPointer,
  inlinePlaceholderImage,
  snapPointToGrid,
  snapPointToObjects,
  toDocCoords as toDocumentCoords,
} from '@andmarruda/svg-editor-adapter-utils';
import { useEditor } from '../hooks/useEditor';
import { useEditorState } from '../hooks/useEditorState';
import { SvgDomRenderer } from '../renderer/SvgDomRenderer';

interface CanvasProps {
  className?: string;
  style?: React.CSSProperties;
  imageHref?: string;
  shapePreset?: ShapePreset;
  snapToGrid?: boolean;
  snapToObjects?: boolean;
  gridSize?: number;
}

export function Canvas({
  className,
  style,
  imageHref = inlinePlaceholderImage(),
  shapePreset = 'star',
  snapToGrid = true,
  snapToObjects = true,
  gridSize = 10,
}: CanvasProps) {
  const editor = useEditor();
  const state = useEditorState();
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<SvgDomRenderer | null>(null);

  // Mount renderer once
  useEffect(() => {
    if (!containerRef.current) return;
    const renderer = new SvgDomRenderer();
    renderer.mount(containerRef.current);
    rendererRef.current = renderer;
    return () => {
      renderer.unmount();
      rendererRef.current = null;
    };
  }, []);

  // Re-render on state change
  useEffect(() => {
    rendererRef.current?.render(state);
  }, [state]);

  // ── Marquee selection state ──────────────────────────────────────────────
  const marqueeRef = useRef<{ startX: number; startY: number; active: boolean }>({
    startX: 0,
    startY: 0,
    active: false,
  });

  const toDocCoords = useCallback(
    (clientX: number, clientY: number) => {
      if (!containerRef.current) return { x: clientX, y: clientY };
      const rect = containerRef.current.getBoundingClientRect();
      return toDocumentCoords(
        { x: clientX, y: clientY },
        rect,
        state.viewTransform.matrix,
        (point) =>
          snapPointToObjects(
            state.document,
            snapPointToGrid(point, gridSize, snapToGrid),
            snapToObjects ? 6 : 0,
          ),
      );
    },
    [gridSize, snapToGrid, snapToObjects, state.document, state.viewTransform],
  );

  const handlePointerDown = useCallback(
    (e: PointerEvent<HTMLDivElement>) => {
      if (state.activeTool !== 'select') return;
      const { x, y } = toDocCoords(e.clientX, e.clientY);
      marqueeRef.current = { startX: x, startY: y, active: true };
      (e.target as HTMLDivElement).setPointerCapture(e.pointerId);
    },
    [state.activeTool, toDocCoords],
  );

  const handlePointerUp = useCallback(
    (e: PointerEvent<HTMLDivElement>) => {
      if (!marqueeRef.current.active) return;
      marqueeRef.current.active = false;

      const { x, y } = toDocCoords(e.clientX, e.clientY);
      const { startX, startY } = marqueeRef.current;
      const dx = Math.abs(x - startX);
      const dy = Math.abs(y - startY);

      if (state.activeTool !== 'select') {
        createNodeFromPointer({
          editor,
          tool: state.activeTool,
          start: { x: startX, y: startY },
          end: { x, y },
          imageHref,
          shapePreset,
          snap: (point) =>
            snapPointToObjects(
              state.document,
              snapPointToGrid(point, gridSize, snapToGrid),
              snapToObjects ? 6 : 0,
            ),
        });
        editor.setActiveTool('select');
        return;
      }

      if (dx < 3 && dy < 3) {
        // Click — hit test
        const hitId = rendererRef.current?.hitTest({ x, y }, state) ?? null;
        if (hitId) {
          editor.selectNode(hitId, e.shiftKey);
        } else {
          editor.deselectAll();
        }
      } else {
        // Marquee
        const box: BoundingBox = {
          x: Math.min(startX, x),
          y: Math.min(startY, y),
          width: Math.abs(x - startX),
          height: Math.abs(y - startY),
        };
        editor.selectByMarquee(box, e.shiftKey);
      }
    },
    [editor, gridSize, imageHref, shapePreset, snapToGrid, snapToObjects, state, toDocCoords],
  );

  // Wheel zoom
  const handleWheel = useCallback(
    (e: React.WheelEvent) => {
      e.preventDefault();
      const scaleDelta = e.deltaY > 0 ? 0.9 : 1.1;
      const [a, b, c, d, et, f] = state.viewTransform.matrix;
      const newA = (a ?? 1) * scaleDelta;
      const newD = (d ?? 1) * scaleDelta;
      editor.setViewTransform({ matrix: [newA, b ?? 0, c ?? 0, newD, et ?? 0, f ?? 0] });
    },
    [editor, state.viewTransform],
  );

  return (
    <div
      ref={containerRef}
      className={className}
      style={{ position: 'relative', overflow: 'hidden', cursor: 'default', ...style }}
      onPointerDown={handlePointerDown}
      onPointerUp={handlePointerUp}
      onWheel={handleWheel}
    />
  );
}

// packages/vue-adapter/src/components/Canvas.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import type { BoundingBox, ShapePreset } from '@andmarruda/svg-editor-core';
import {
  createNodeFromPointer,
  inlinePlaceholderImage,
  snapPointToGrid,
  snapPointToObjects,
  toDocCoords,
} from '@andmarruda/svg-editor-adapter-utils';
import { SvgDomRenderer } from '../renderer/SvgDomRenderer';
import { useEditor } from '../composables/useEditor';
import { useEditorState } from '../composables/useEditorState';

const props = withDefaults(
  defineProps<{
    imageHref?: string;
    shapePreset?: ShapePreset;
    snapToGrid?: boolean;
    snapToObjects?: boolean;
    gridSize?: number;
  }>(),
  {
    imageHref: () => inlinePlaceholderImage(),
    shapePreset: 'star',
    snapToGrid: true,
    snapToObjects: true,
    gridSize: 10,
  },
);

const editor = useEditor();
const state = useEditorState();
const root = ref<HTMLDivElement | null>(null);
const renderer = ref<SvgDomRenderer | null>(null);
const marquee = { startX: 0, startY: 0, active: false };

function docPoint(event: PointerEvent) {
  if (!root.value) return { x: event.clientX, y: event.clientY };
  return toDocCoords(
    { x: event.clientX, y: event.clientY },
    root.value.getBoundingClientRect(),
    state.value.viewTransform.matrix,
    (point) =>
      snapPointToObjects(
        state.value.document,
        snapPointToGrid(point, props.gridSize, props.snapToGrid),
        props.snapToObjects ? 6 : 0,
      ),
  );
}

function onPointerDown(event: PointerEvent) {
  if (state.value.activeTool !== 'select') return;
  const point = docPoint(event);
  marquee.startX = point.x;
  marquee.startY = point.y;
  marquee.active = true;
  (event.currentTarget as HTMLDivElement).setPointerCapture(event.pointerId);
}

function onPointerUp(event: PointerEvent) {
  if (!marquee.active) return;
  marquee.active = false;
  const point = docPoint(event);
  const dx = Math.abs(point.x - marquee.startX);
  const dy = Math.abs(point.y - marquee.startY);

  if (state.value.activeTool !== 'select') {
    createNodeFromPointer({
      editor,
      tool: state.value.activeTool,
      start: { x: marquee.startX, y: marquee.startY },
      end: point,
      imageHref: props.imageHref,
      shapePreset: props.shapePreset,
      snap: (candidate) =>
        snapPointToObjects(
          state.value.document,
          snapPointToGrid(candidate, props.gridSize, props.snapToGrid),
          props.snapToObjects ? 6 : 0,
        ),
    });
    editor.setActiveTool('select');
    return;
  }

  if (dx < 3 && dy < 3) {
    const hitId = renderer.value?.hitTest(point, state.value) ?? null;
    if (hitId) editor.selectNode(hitId, event.shiftKey);
    else editor.deselectAll();
    return;
  }

  const box: BoundingBox = {
    x: Math.min(marquee.startX, point.x),
    y: Math.min(marquee.startY, point.y),
    width: Math.abs(point.x - marquee.startX),
    height: Math.abs(point.y - marquee.startY),
  };
  editor.selectByMarquee(box, event.shiftKey);
}

function onWheel(event: WheelEvent) {
  event.preventDefault();
  const scaleDelta = event.deltaY > 0 ? 0.9 : 1.1;
  const [a, b, c, d, e, f] = state.value.viewTransform.matrix;
  editor.setViewTransform({
    matrix: [(a ?? 1) * scaleDelta, b ?? 0, c ?? 0, (d ?? 1) * scaleDelta, e ?? 0, f ?? 0],
  });
}

onMounted(() => {
  if (!root.value) return;
  const next = new SvgDomRenderer();
  next.mount(root.value);
  renderer.value = next;
  next.render(state.value);
});

watch(state, (next) => renderer.value?.render(next), { deep: true });
onBeforeUnmount(() => renderer.value?.unmount());
</script>

<template>
  <div
    ref="root"
    style="position: relative; overflow: hidden; cursor: default; width: 100%; height: 100%"
    @pointerdown="onPointerDown"
    @pointerup="onPointerUp"
    @wheel="onWheel"
  />
</template>
